import { createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
const SECRET = process.env.JWT_SECRET || "dev-secret-cambia-esto-en-produccion";
function b64url(input) { return Buffer.from(input).toString("base64").replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function fromB64url(input) { const padded = input.replaceAll("-", "+").replaceAll("_", "/") + "===".slice((input.length + 3) % 4); return Buffer.from(padded, "base64").toString("utf8"); }
export function hashPassword(password) { const salt = randomBytes(16).toString("hex"); return `${salt}:${scryptSync(password, salt, 32).toString("hex")}`; }
export function verifyPassword(password, stored) { const [salt, hash] = String(stored).split(":"); if (!salt || !hash) return false; const next = scryptSync(password, salt, 32); const prev = Buffer.from(hash, "hex"); return prev.length === next.length && timingSafeEqual(prev, next); }
export function signToken(user, expiresInSec = 60 * 60 * 24 * 7) { const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" })); const payload = b64url(JSON.stringify({ id: user.id, username: user.username, exp: Math.floor(Date.now() / 1000) + expiresInSec })); const data = `${header}.${payload}`; return `${data}.${createHmac("sha256", SECRET).update(data).digest("base64url")}`; }
export function verifyToken(token) { const parts = String(token || "").split("."); if (parts.length !== 3) return null; const [header, payload, sig] = parts; const expected = createHmac("sha256", SECRET).update(`${header}.${payload}`).digest("base64url"); const a = Buffer.from(sig); const b = Buffer.from(expected); if (a.length !== b.length || !timingSafeEqual(a, b)) return null; try { const data = JSON.parse(fromB64url(payload)); if (!data.exp || data.exp < Math.floor(Date.now() / 1000)) return null; return data; } catch { return null; } }
export function getUserFromRequest(req) { const header = req.headers.authorization || ""; return verifyToken(header.startsWith("Bearer ") ? header.slice(7) : ""); }
